### ISSUE TITLE
Problem in updated context.py

### ISSUE THREAD

**Issue by jorana** [AxFoundation/strax#226]
While running bootstrax, I encountered a bug in a new feature of strax. The 'run_defaults' in context.py is returning a None somewhere. I've added the error message below. I'm at the moment circumventing this problem by disabling line https://github.com/AxFoundation/strax/blob/master/strax/context.py#L330 as follows:
```
def _set_plugin_config(self, p, run_id, tolerant=True):
        # Explicit type check, since if someone calls this with
        # plugin CLASSES, funny business might ensue
        assert isinstance(p, strax.Plugin)
        config = self.config.copy()
        for opt in p.takes_config.values():
            try:
                opt.validate(config,
                             run_id=run_id,
#                              run_defaults=self.run_defaults(run_id)
                            )
            except strax.InvalidConfiguration:
                if not tolerant:
                    raise
        p.config = {k: v for k, v in config.items()
                    if k in p.takes_config}
```

The full traceback of the error message message:
```
18364 MainThread root New failure on run 6102:5deddb9b7a302de2ad97eb5e: Strax exited with exit code 1. Exception info: Traceback (most recent call last):
  File "bootstrax.py", line 556, in run_strax
    max_workers=args.cores)
  File "/home/xedaq/software/strax/strax/context.py", line 881, in make
    if _skip_if_built and self.is_stored(run_id, targets):
  File "/home/xedaq/software/strax/strax/context.py", line 1001, in is_stored
    key = self.key_for(run_id, target)
  File "/home/xedaq/software/strax/strax/context.py", line 926, in key_for
    p = self._get_plugins((target,), run_id)[target]
  File "/home/xedaq/software/strax/strax/context.py", line 414, in _get_plugins
    p = get_plugin(t)
  File "/home/xedaq/software/strax/strax/context.py", line 371, in get_plugin
    self._set_plugin_config(p, run_id, tolerant=True)
  File "/home/xedaq/software/strax/strax/context.py", line 330, in _set_plugin_config
    run_defaults=self.run_defaults(run_id))
  File "/home/xedaq/software/strax/strax/context.py", line 977, in run_defaults
    projection=RUN_DEFAULTS_KEY).get(RUN_DEFAULTS_KEY, dict())
  File "/home/xedaq/software/strax/strax/context.py", line 959, in run_metadata
    return sf.run_metadata(run_id, projection=projection)
  File "/home/xedaq/software/straxen/straxen/rundb.py", line 235, in run_metadata
    doc['mode'] = doc.get('reader', {}).get('ini', {}).get('name', '')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by JelleAalbers** [comment]
Hi Joran, thanks for spotting this! I think it was an issue with the straxen RunDB backend (see https://github.com/XENONnT/straxen/commit/c7d66744a6af7d06863067fd0c5c4b79f369b815) that only surfaced now because we did not look at the run doc for processing. Can you try with the latest straxen master now?

**Comment by jorana** [comment]
Thanks for your quick followup Jelle, it works now.
