### ISSUE TITLE
Mailbox hang not propegated correctly down the chain

### ISSUE THREAD

**Issue by jorana** [AxFoundation/strax#282]
**Problem**
A mailbox hang is not propagated down the processing chain correctly. 

**Symptoms**
Despite a run-time error processing continues on the eventbuilders without proper crashing.

**Possibly related**
- We decreased the chunk size from 5+0.5 s to 1.6+0.4 s
- The cause might be related to rsync instances on eb3

**Not related**
_edit: I thought that either of these might have been related but this is not the case_
- [NOT RELATED*] Perhaps this issue was sparked by https://github.com/XENONnT/straxen/pull/146 further investigation may be required. I've merged this PR just before this issue became apparent.
- [NOT RELATED*] High data-rates in combination with the LED plugin. The LED https://github.com/XENONnT/straxen/blob/master/straxen/plugins/led_calibration.py is particularly RAM hungry. Perhaps at high datarates we run into insufficient RAM issues when trying to process this plugin multicore.

*Both are not related as tests have shown the error persists if either is is disabled

**The error**
```
775469 MainThread root Still processing run 008563
Process Process-1:
Traceback (most recent call last):
  File "/home/xedaq/miniconda/envs/py37/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/xedaq/miniconda/envs/py37/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xedaq/software/straxen/bin/bootstrax", line 1039, in run_strax
    st_make()
  File "/home/xedaq/software/straxen/bin/bootstrax", line 1036, in st_make
    max_workers=process_mode['cores'])
  File "/home/xedaq/software/strax/strax/context.py", line 921, in make
    save=save, max_workers=max_workers, **kwargs):
  File "/home/xedaq/software/strax/strax/context.py", line 830, in get_iter
    generator.throw(e)
  File "/home/xedaq/software/strax/strax/context.py", line 811, in get_iter
    for result in strax.continuity_check(generator):
  File "/home/xedaq/software/strax/strax/chunk.py", line 251, in continuity_check
    for s in chunk_iter:
  File "/home/xedaq/software/strax/strax/processor.py", line 254, in iter
    m.cleanup()
  File "/home/xedaq/software/strax/strax/mailbox.py", line 206, in cleanup
    raise RuntimeError("Thread %s did not terminate!" % t.name)
RuntimeError: Thread save_0:raw_records did not terminate!
785489 MainThread root Still processing run 008563
```

**Software/hardware**
eb3
python 3.7
strax v 0.11.1
straxen v0.9.1
bootstrax options:
```cores=20, max_messages=15, timeout=200```

**Comment by jorana** [comment]
From experience we have now learned that it was due to:
```The cause might be related to rsync instances on eb3```` 

Closing this issue as there is no to little opportunity for strax to improve
