### ISSUE TITLE
Pickling error related to numba caching of find_split_points

### ISSUE THREAD

**Issue by JelleAalbers** [AxFoundation/strax#45]
I just had a strange experience running strax on eb1. After clearling `__pycache__ ` in the `strax/processing` folder, it would give me a numba lowering error, followed (strangely) by a multiprocessing pickling error.
```
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
int64 generator(func=<function find_split_points at 0x7fc5dcdb2ae8>, args=(array(float32, 1d, C), int64, int64), has_finalizer=True)
File "../strax/processing/peak_splitting.py", line 42
[1] During: lowering "$70.2 = iternext(value=$phi70.1)" at /home/xedaq/strax/strax/processing/peak_splitting.py (42)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xedaq/anaconda3/envs/36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/xedaq/anaconda3/envs/36/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xedaq/anaconda3/envs/36/lib/python3.6/concurrent/futures/process.py", line 178, in _process_worker
    result_queue.put(_ResultItem(call_item.work_id, exception=exc))
  File "/home/xedaq/anaconda3/envs/36/lib/python3.6/multiprocessing/queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "/home/xedaq/anaconda3/envs/36/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function find_split_points at 0x7fc5e3d7bd90>: it's not the same object as strax.processing.peak_splitting.find_split_points
```
Removing cache=True on find_split_points resolved the issue. Deleting `__pycache__` and restoring cache=True reproduced it; removing cache=True fixed it again. Then, after checking out another git commit (maybe triggering recompilation due to modification times) it worked even with cache=True.

The performance penalty of recompiling this one function in every process is small, so we can remove cache=True if anyone else sees this problem. I've never seen it on Travis though.

I thought it was some race condition where multiple processes with numba try to compile the same function, but I see it even with max_workers=1, when only one process should be compiling the function at a time (but a ProcessPool is still used, not sure if that has special handling for the n=1 case).

**Comment by tunnell** [comment]
Is this reproducible?  No action required so close and leave for posterity?

**Comment by JelleAalbers** [comment]
Yes, let's archive it.
